id: P16A78071
initial_creation_type: input
source_metadata:
  title: Do Khyentse Yeshe Dorje Series
  language: bo
  description: 'A series of texts associated with the treasure-revealer Do Khyentse
    Yeshe Dorje (mdo mkhyen brtse ye shes rdo rje, 1800–1866), renowned as the ''mind
    emanation'' of Jigme Lingpa:'
  volume:
    6098ad18ee2542dd890f6b2c2a0d832a:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Aspiration Prayers
    f0b560ef31a24f66aa05ad6773a9450d:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Confession
    fe86b9ecc51e424cbd290227e6b0fd07:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Guru Rinpoche Prayers
    fea1debc81d841718be1cfc9995ef704:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Guru Rinpoche Prayers
    c04e3520b55e4afca0e71ed9df034d53:
      title: The Lineage Prayer for the Natural Liberation of Grasping (Dzinpa Rangdrol)
      parent: Lineage Prayers
    a6b90f8fb2d449a29c42d584ef2f22ea:
      title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and
        Liberation of Rigdzin Jalü Dorje'
      parent: Prayers
    68c7cdd8887e4b72ad84dd0c4e92d9a4:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Preliminaries
created_at: '2022-02-28T22:55:15.002342'
last_modified_at: '2022-02-28T22:55:15.002345'
statistics:
  total_words: 5426
  total_non_words: 450
quality:
  non_words_ratio: 0.08
